[package]
name = "tts-air-ipc"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.19"

[dependencies.windows-sys]
version = "0.48"
features = [
    "Win32_Foundation",
    "Win32_System_Pipes",
    "Win32_System_IO",
    "Win32_Security",
    "Win32_Storage_FileSystem",
]